import type {
  ExerciseDefinition,
  ExerciseKey,
  MovementPattern,
  MuscleTag,
  RoleTag,
} from "./exerciseTypes";
import type { Slot } from "./slotTypes";

function normalizeAlias(input: string): string {
  return String(input || "")
    .trim()
    .toLowerCase()
    .replace(/[()]/g, "")
    .replace(/[\s-]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
}

type ExerciseSeedInput = {
  key: ExerciseKey;
  canonicalName: string;
  aliases?: string[];
  movementPatterns: MovementPattern[];
  primaryMuscles: MuscleTag[];
  secondaryMuscles?: MuscleTag[];
  equipment: ExerciseDefinition["equipment"];
  roleTags: RoleTag[];
  family: string;
  fatigue: ExerciseDefinition["fatigue"];
  compound: boolean;
  unilateral?: boolean;
};

function seedExercise(input: ExerciseSeedInput): ExerciseDefinition {
  const aliases = new Set<string>([
    input.key,
    input.canonicalName,
    ...(input.aliases ?? []),
  ].map(normalizeAlias).filter(Boolean));

  return {
    id: input.key,
    key: input.key,
    canonicalName: input.canonicalName,
    aliases: [...aliases],
    movementPatterns: [...input.movementPatterns],
    primaryMuscles: [...input.primaryMuscles],
    secondaryMuscles: [...(input.secondaryMuscles ?? [])],
    equipment: [...input.equipment],
    roleTags: [...input.roleTags],
    family: input.family,
    fatigue: input.fatigue,
    compound: input.compound,
    unilateral: input.unilateral,
    active: true,
  };
}

const EXERCISES: ExerciseDefinition[] = [
  seedExercise({
    key: "bench_press",
    canonicalName: "Bench Press",
    aliases: ["bench", "barbell bench press"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["barbell", "bench", "rack"],
    roleTags: ["anchor", "primary"],
    family: "horizontal_press",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "incline_bench_press",
    canonicalName: "Incline Bench Press",
    aliases: ["incline bench", "incline barbell bench press"],
    movementPatterns: ["horizontal_push", "vertical_push"],
    primaryMuscles: ["chest", "front_delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["barbell", "bench", "rack"],
    roleTags: ["primary", "secondary"],
    family: "horizontal_press",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "dumbbell_bench_press",
    canonicalName: "DB Bench Press",
    aliases: ["db bench press", "dumbbell bench", "flat dumbbell press"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["dumbbell", "bench"],
    roleTags: ["primary", "secondary"],
    family: "horizontal_press",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "chest_press",
    canonicalName: "Chest Press",
    aliases: ["machine chest press"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["machine"],
    roleTags: ["primary", "secondary"],
    family: "horizontal_press",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "overhead_press",
    canonicalName: "Overhead Press",
    aliases: ["ohp", "standing overhead press"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["front_delts", "triceps"],
    secondaryMuscles: ["chest"],
    equipment: ["barbell", "rack"],
    roleTags: ["primary", "secondary"],
    family: "vertical_press",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "shoulder_press",
    canonicalName: "Shoulder Press",
    aliases: ["machine shoulder press", "db shoulder press"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["machine", "dumbbell"],
    roleTags: ["secondary", "accessory"],
    family: "vertical_press",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "lateral_raise",
    canonicalName: "Lateral Raise",
    aliases: ["db lateral raise", "side lateral raise"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "side_delt_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "rear_delt_fly",
    canonicalName: "Rear Delt Fly",
    aliases: ["rear delt raise", "reverse fly"],
    movementPatterns: ["rear_delt"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["upper_back"],
    equipment: ["dumbbell", "machine", "cable"],
    roleTags: ["accessory", "pump"],
    family: "rear_delt_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "dip",
    canonicalName: "Dip",
    aliases: ["weighted dip", "bodyweight dip"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["front_delts"],
    equipment: ["bodyweight", "other"],
    roleTags: ["secondary", "accessory"],
    family: "dip_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "triceps_pressdown",
    canonicalName: "Triceps Pressdown",
    aliases: ["pressdown", "cable pressdown"],
    movementPatterns: ["elbow_extension"],
    primaryMuscles: ["triceps"],
    equipment: ["cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "triceps_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "overhead_triceps_extension",
    canonicalName: "Overhead Triceps Extension",
    aliases: ["overhead extension", "triceps extension"],
    movementPatterns: ["elbow_extension"],
    primaryMuscles: ["triceps"],
    equipment: ["dumbbell", "cable", "band"],
    roleTags: ["accessory"],
    family: "triceps_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "skullcrusher",
    canonicalName: "Skullcrusher",
    aliases: ["lying triceps extension", "skull crusher"],
    movementPatterns: ["elbow_extension"],
    primaryMuscles: ["triceps"],
    equipment: ["barbell", "dumbbell", "bench"],
    roleTags: ["accessory"],
    family: "triceps_isolation",
    fatigue: "medium",
    compound: false,
  }),
  seedExercise({
    key: "push_up",
    canonicalName: "Push-Up",
    aliases: ["pushup", "push ups", "pushups"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["bodyweight"],
    roleTags: ["pump", "accessory"],
    family: "horizontal_press",
    fatigue: "low",
    compound: true,
  }),
  seedExercise({
    key: "pec_deck",
    canonicalName: "Pec Deck",
    aliases: ["pec fly", "machine fly"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    equipment: ["machine"],
    roleTags: ["pump", "accessory"],
    family: "chest_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "barbell_row",
    canonicalName: "Barbell Row",
    aliases: ["bent over row", "bb row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["barbell"],
    roleTags: ["anchor", "primary"],
    family: "row_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "chest_supported_row",
    canonicalName: "Chest Supported Row",
    aliases: ["supported row", "chest-supported row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["bench", "dumbbell", "machine"],
    roleTags: ["anchor", "primary", "secondary"],
    family: "row_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "seated_cable_row",
    canonicalName: "Seated Cable Row",
    aliases: ["cable row", "seated row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
    roleTags: ["anchor", "primary", "secondary"],
    family: "row_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "t_bar_row",
    canonicalName: "T-Bar Row",
    aliases: ["tbar row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["barbell", "machine", "other"],
    roleTags: ["anchor", "primary"],
    family: "row_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "pull_up",
    canonicalName: "Pull-Up",
    aliases: ["pullup", "pull up"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps"],
    equipment: ["bodyweight", "other"],
    roleTags: ["anchor", "primary"],
    family: "vertical_pull_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "chin_up",
    canonicalName: "Chin-Up",
    aliases: ["chinup", "chin up"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["upper_back"],
    equipment: ["bodyweight", "other"],
    roleTags: ["anchor", "primary"],
    family: "vertical_pull_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "lat_pulldown",
    canonicalName: "Lat Pulldown",
    aliases: ["pulldown", "lat pull down", "lat pull"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["upper_back", "biceps"],
    equipment: ["cable", "machine", "band"],
    roleTags: ["anchor", "primary", "secondary"],
    family: "vertical_pull_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "assisted_pull_up",
    canonicalName: "Assisted Pull-Up",
    aliases: ["band assisted pull up", "assisted pullup"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps"],
    equipment: ["machine", "band", "bodyweight"],
    roleTags: ["primary", "secondary"],
    family: "vertical_pull_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "one_arm_dumbbell_row",
    canonicalName: "One-Arm DB Row",
    aliases: ["one arm row", "single arm dumbbell row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbell", "bench"],
    roleTags: ["secondary", "accessory"],
    family: "row_pattern",
    fatigue: "medium",
    compound: true,
    unilateral: true,
  }),
  seedExercise({
    key: "face_pull",
    canonicalName: "Face Pull",
    aliases: ["rope face pull"],
    movementPatterns: ["rear_delt"],
    primaryMuscles: ["rear_delts", "upper_back"],
    equipment: ["cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "rear_delt_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "reverse_pec_deck",
    canonicalName: "Reverse Pec Deck",
    aliases: ["reverse fly machine"],
    movementPatterns: ["rear_delt"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["upper_back"],
    equipment: ["machine"],
    roleTags: ["accessory", "pump"],
    family: "rear_delt_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "band_pull_apart",
    canonicalName: "Band Pull-Apart",
    aliases: ["band pull apart", "pull apart"],
    movementPatterns: ["rear_delt"],
    primaryMuscles: ["rear_delts", "upper_back"],
    equipment: ["band"],
    roleTags: ["accessory", "pump"],
    family: "rear_delt_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "hammer_curl",
    canonicalName: "Hammer Curl",
    aliases: ["db hammer curl"],
    movementPatterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["upper_back"],
    equipment: ["dumbbell", "cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "biceps_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "curl",
    canonicalName: "Curl",
    aliases: ["barbell curl", "biceps curl"],
    movementPatterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    equipment: ["barbell", "dumbbell", "cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "biceps_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "incline_dumbbell_curl",
    canonicalName: "Incline DB Curl",
    aliases: ["incline curl", "incline dumbbell biceps curl"],
    movementPatterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    equipment: ["dumbbell", "bench"],
    roleTags: ["accessory"],
    family: "biceps_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "preacher_curl",
    canonicalName: "Preacher Curl",
    aliases: ["preacher curl machine"],
    movementPatterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    equipment: ["barbell", "dumbbell", "machine"],
    roleTags: ["accessory"],
    family: "biceps_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "ssb_squat",
    canonicalName: "SSB Squat",
    aliases: ["safety squat bar squat", "safety squat"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["ssb", "rack"],
    roleTags: ["anchor", "primary"],
    family: "squat_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "squat",
    canonicalName: "Squat",
    aliases: ["barbell squat", "back squat"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "rack"],
    roleTags: ["anchor", "primary"],
    family: "squat_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "romanian_deadlift",
    canonicalName: "Romanian Deadlift",
    aliases: ["rdl"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["upper_back"],
    equipment: ["barbell", "dumbbell"],
    roleTags: ["anchor", "primary"],
    family: "hinge_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "deadlift",
    canonicalName: "Deadlift",
    aliases: ["conventional deadlift"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes", "upper_back"],
    equipment: ["barbell"],
    roleTags: ["anchor", "primary"],
    family: "hinge_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "good_morning",
    canonicalName: "Good Morning",
    aliases: ["barbell good morning"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["upper_back"],
    equipment: ["barbell", "rack"],
    roleTags: ["secondary", "accessory"],
    family: "hinge_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "hamstring_curl",
    canonicalName: "Hamstring Curl",
    aliases: ["leg curl", "lying leg curl"],
    movementPatterns: ["knee_flexion", "hinge"],
    primaryMuscles: ["hamstrings"],
    equipment: ["machine", "band"],
    roleTags: ["secondary", "accessory"],
    family: "hamstring_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "leg_extension",
    canonicalName: "Leg Extension",
    aliases: ["quad extension"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads"],
    equipment: ["machine", "band", "other"],
    roleTags: ["secondary", "accessory"],
    family: "quad_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "split_squat",
    canonicalName: "Split Squat",
    aliases: ["bulgarian split squat", "split squat rear foot elevated"],
    movementPatterns: ["lunge"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbell", "barbell", "bodyweight"],
    roleTags: ["secondary", "accessory"],
    family: "lunge_pattern",
    fatigue: "medium",
    compound: true,
    unilateral: true,
  }),
  seedExercise({
    key: "glute_ham_raise",
    canonicalName: "Glute-Ham Raise",
    aliases: ["ghr", "glute ham raise"],
    movementPatterns: ["knee_flexion", "hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    equipment: ["machine", "other"],
    roleTags: ["secondary", "accessory"],
    family: "hamstring_isolation",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "seated_leg_curl",
    canonicalName: "Seated Leg Curl",
    aliases: ["seated hamstring curl"],
    movementPatterns: ["knee_flexion", "hinge"],
    primaryMuscles: ["hamstrings"],
    equipment: ["machine"],
    roleTags: ["secondary", "accessory"],
    family: "hamstring_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "calf_raise",
    canonicalName: "Standing Calf Raise",
    aliases: ["standing calf raise"],
    movementPatterns: ["calves"],
    primaryMuscles: ["calves"],
    equipment: ["machine", "bodyweight", "barbell", "dumbbell"],
    roleTags: ["accessory", "pump"],
    family: "calf_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "seated_calf_raise",
    canonicalName: "Seated Calf Raise",
    aliases: [],
    movementPatterns: ["calves"],
    primaryMuscles: ["calves"],
    equipment: ["machine", "other"],
    roleTags: ["accessory", "pump"],
    family: "calf_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "leg_press_calf_raise",
    canonicalName: "Leg Press Calf Raise",
    aliases: ["calf press"],
    movementPatterns: ["calves"],
    primaryMuscles: ["calves"],
    equipment: ["machine"],
    roleTags: ["accessory", "pump"],
    family: "calf_isolation",
    fatigue: "low",
    compound: false,
  }),

  seedExercise({
    key: "close_grip_bench_press",
    canonicalName: "Close-Grip Bench Press",
    aliases: ["close grip bench", "cgbp"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_delts"],
    equipment: ["barbell", "bench", "rack"],
    roleTags: ["primary", "secondary"],
    family: "horizontal_press",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "paused_bench_press",
    canonicalName: "Paused Bench Press",
    aliases: ["pause bench", "comp pause bench"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["barbell", "bench", "rack"],
    roleTags: ["primary", "secondary"],
    family: "horizontal_press",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "feet_up_bench_press",
    canonicalName: "Feet-Up Bench Press",
    aliases: ["feet up bench", "feet-up bench"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["barbell", "bench", "rack"],
    roleTags: ["secondary"],
    family: "horizontal_press",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "larsen_press",
    canonicalName: "Larsen Press",
    aliases: ["larsen bench", "feet-off bench"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["barbell", "bench", "rack"],
    roleTags: ["secondary"],
    family: "horizontal_press",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "incline_dumbbell_press",
    canonicalName: "Incline DB Press",
    aliases: ["incline db press", "incline dumbbell bench"],
    movementPatterns: ["horizontal_push", "vertical_push"],
    primaryMuscles: ["chest", "front_delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbell", "bench"],
    roleTags: ["primary", "secondary"],
    family: "horizontal_press",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "weighted_push_up",
    canonicalName: "Weighted Push-Up",
    aliases: ["weighted pushup"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["bodyweight", "other"],
    roleTags: ["secondary", "pump"],
    family: "horizontal_press",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "band_resisted_push_up",
    canonicalName: "Band-Resisted Push-Up",
    aliases: ["band pushup", "resisted push up"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["bodyweight", "band"],
    roleTags: ["secondary", "pump"],
    family: "horizontal_press",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "seated_dumbbell_press",
    canonicalName: "Seated DB Press",
    aliases: ["seated db shoulder press", "seated dumbbell shoulder press"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbell", "bench"],
    roleTags: ["secondary"],
    family: "vertical_press",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "arnold_press",
    canonicalName: "Arnold Press",
    aliases: ["db arnold press"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["front_delts", "side_delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbell", "bench"],
    roleTags: ["secondary", "accessory"],
    family: "vertical_press",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "leaning_lateral_raise",
    canonicalName: "Leaning Lateral Raise",
    aliases: ["lean away lateral raise"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["side_delts"],
    equipment: ["dumbbell", "cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "side_delt_isolation",
    fatigue: "low",
    compound: false,
    unilateral: true,
  }),
  seedExercise({
    key: "cable_lateral_raise",
    canonicalName: "Cable Lateral Raise",
    aliases: ["single arm cable lateral raise"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["side_delts"],
    equipment: ["cable"],
    roleTags: ["accessory", "pump"],
    family: "side_delt_isolation",
    fatigue: "low",
    compound: false,
    unilateral: true,
  }),
  seedExercise({
    key: "front_raise",
    canonicalName: "Front Raise",
    aliases: ["db front raise", "plate front raise"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["front_delts"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "band", "cable", "other"],
    roleTags: ["accessory", "pump"],
    family: "front_delt_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "underhand_barbell_row",
    canonicalName: "Underhand Barbell Row",
    aliases: ["supinated barbell row", "underhand row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps"],
    equipment: ["barbell"],
    roleTags: ["anchor", "primary"],
    family: "row_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "incline_dumbbell_row",
    canonicalName: "Incline DB Row",
    aliases: ["incline chest supported row", "incline row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbell", "bench"],
    roleTags: ["primary", "secondary"],
    family: "row_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "seal_row",
    canonicalName: "Seal Row",
    aliases: ["seal barbell row", "seal dumbbell row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["bench", "dumbbell", "barbell"],
    roleTags: ["anchor", "primary"],
    family: "row_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "band_row",
    canonicalName: "Band Row",
    aliases: ["resistance band row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["band"],
    roleTags: ["secondary", "accessory"],
    family: "row_pattern",
    fatigue: "low",
    compound: true,
  }),
  seedExercise({
    key: "scapular_row",
    canonicalName: "Scapular Row",
    aliases: ["retraction row", "scap row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["rear_delts"],
    equipment: ["band", "cable", "dumbbell"],
    roleTags: ["accessory", "pump"],
    family: "scapular_control",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "lat_focus_row",
    canonicalName: "Lat-Focus Row",
    aliases: ["lat biased row", "elbow tucked row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["upper_back", "biceps"],
    equipment: ["dumbbell", "cable", "band", "bench"],
    roleTags: ["secondary", "accessory"],
    family: "row_pattern",
    fatigue: "medium",
    compound: true,
    unilateral: true,
  }),
  seedExercise({
    key: "weighted_pull_up",
    canonicalName: "Weighted Pull-Up",
    aliases: ["weighted pullup"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps"],
    equipment: ["bodyweight", "other"],
    roleTags: ["anchor", "primary"],
    family: "vertical_pull_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "weighted_chin_up",
    canonicalName: "Weighted Chin-Up",
    aliases: ["weighted chinup"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["upper_back"],
    equipment: ["bodyweight", "other"],
    roleTags: ["anchor", "primary"],
    family: "vertical_pull_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "band_assisted_chin_up",
    canonicalName: "Band-Assisted Chin-Up",
    aliases: ["assisted chin up", "assisted chinup"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["upper_back"],
    equipment: ["bodyweight", "band", "other"],
    roleTags: ["secondary"],
    family: "vertical_pull_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "straight_arm_pulldown",
    canonicalName: "Straight-Arm Pulldown",
    aliases: ["straight arm pull down", "lat prayer"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["upper_back"],
    equipment: ["cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "lat_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "dumbbell_pullover",
    canonicalName: "DB Pullover",
    aliases: ["pullover", "db pullover"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["chest", "upper_back"],
    equipment: ["dumbbell", "bench"],
    roleTags: ["secondary", "accessory"],
    family: "lat_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "barbell_shrug",
    canonicalName: "Barbell Shrug",
    aliases: ["bb shrug"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    roleTags: ["accessory", "pump"],
    family: "trap_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "dumbbell_shrug",
    canonicalName: "DB Shrug",
    aliases: ["db shrug", "dumbbell shrug"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    roleTags: ["accessory", "pump"],
    family: "trap_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "behind_back_shrug",
    canonicalName: "Behind-the-Back Shrug",
    aliases: ["behind the back shrug"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    roleTags: ["accessory", "pump"],
    family: "trap_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "band_shrug",
    canonicalName: "Band Shrug",
    aliases: ["resistance band shrug"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back"],
    secondaryMuscles: [],
    equipment: ["band"],
    roleTags: ["accessory", "pump"],
    family: "trap_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "prone_y_raise",
    canonicalName: "Prone Y Raise",
    aliases: ["y raise", "lower trap raise"],
    movementPatterns: ["rear_delt"],
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["rear_delts"],
    equipment: ["dumbbell", "bench", "band"],
    roleTags: ["accessory", "pump"],
    family: "scapular_control",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "trap_3_raise",
    canonicalName: "Trap-3 Raise",
    aliases: ["trap 3 raise", "incline trap raise"],
    movementPatterns: ["rear_delt"],
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["rear_delts"],
    equipment: ["dumbbell", "bench", "band"],
    roleTags: ["accessory", "pump"],
    family: "scapular_control",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "incline_rear_delt_raise",
    canonicalName: "Incline Rear Delt Raise",
    aliases: ["incline rear delt fly"],
    movementPatterns: ["rear_delt"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["upper_back"],
    equipment: ["dumbbell", "bench", "band"],
    roleTags: ["accessory", "pump"],
    family: "rear_delt_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "rear_delt_row",
    canonicalName: "Rear Delt Row",
    aliases: ["wide elbow row", "rear delt db row"],
    movementPatterns: ["rear_delt", "horizontal_pull"],
    primaryMuscles: ["rear_delts", "upper_back"],
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbell", "cable", "band", "bench"],
    roleTags: ["accessory"],
    family: "rear_delt_isolation",
    fatigue: "low",
    compound: true,
  }),
  seedExercise({
    key: "serratus_pushdown",
    canonicalName: "Serratus Pushdown",
    aliases: ["serratus pulldown", "scap pushdown"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["other"],
    secondaryMuscles: ["lats", "upper_back"],
    equipment: ["cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "scapular_control",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "scapular_push_up",
    canonicalName: "Scapular Push-Up",
    aliases: ["scap push up", "push-up plus"],
    movementPatterns: ["other"],
    primaryMuscles: ["other"],
    secondaryMuscles: ["chest", "upper_back"],
    equipment: ["bodyweight", "band"],
    roleTags: ["accessory", "pump"],
    family: "scapular_control",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "wall_slide",
    canonicalName: "Wall Slide",
    aliases: ["band wall slide", "serratus wall slide"],
    movementPatterns: ["other"],
    primaryMuscles: ["other"],
    secondaryMuscles: ["upper_back"],
    equipment: ["bodyweight", "band", "other"],
    roleTags: ["accessory", "pump"],
    family: "scapular_control",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "scapular_pull_up",
    canonicalName: "Scapular Pull-Up",
    aliases: ["scap pull up", "active hang shrug"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["lats"],
    equipment: ["bodyweight", "other"],
    roleTags: ["accessory", "pump"],
    family: "scapular_control",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "high_bar_squat",
    canonicalName: "High-Bar Squat",
    aliases: ["high bar squat"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "rack"],
    roleTags: ["anchor", "primary"],
    family: "squat_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "box_squat",
    canonicalName: "Box Squat",
    aliases: ["to box squat"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "rack", "bench"],
    roleTags: ["primary", "secondary"],
    family: "squat_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "goblet_squat",
    canonicalName: "Goblet Squat",
    aliases: ["db goblet squat"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbell"],
    roleTags: ["secondary", "accessory"],
    family: "squat_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "heel_elevated_squat",
    canonicalName: "Heel-Elevated Squat",
    aliases: ["cyclist squat"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: ["dumbbell", "barbell", "bodyweight", "other"],
    roleTags: ["secondary", "accessory"],
    family: "squat_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "leverage_squat",
    canonicalName: "Leverage Squat",
    aliases: ["lever squat", "machine squat"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["machine", "other"],
    roleTags: ["primary", "secondary"],
    family: "squat_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "bulgarian_split_squat",
    canonicalName: "Bulgarian Split Squat",
    aliases: ["rear foot elevated split squat", "rfess"],
    movementPatterns: ["lunge"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbell", "barbell", "bench", "bodyweight"],
    roleTags: ["secondary", "accessory"],
    family: "lunge_pattern",
    fatigue: "medium",
    compound: true,
    unilateral: true,
  }),
  seedExercise({
    key: "step_up",
    canonicalName: "Step-Up",
    aliases: ["db step up", "stepup"],
    movementPatterns: ["lunge"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbell", "bench", "bodyweight"],
    roleTags: ["secondary", "accessory"],
    family: "lunge_pattern",
    fatigue: "medium",
    compound: true,
    unilateral: true,
  }),
  seedExercise({
    key: "stiff_leg_deadlift",
    canonicalName: "Stiff-Leg Deadlift",
    aliases: ["sldl", "stiff leg deadlift"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["upper_back"],
    equipment: ["barbell", "dumbbell"],
    roleTags: ["primary", "secondary"],
    family: "hinge_pattern",
    fatigue: "high",
    compound: true,
  }),
  seedExercise({
    key: "hip_thrust",
    canonicalName: "Hip Thrust",
    aliases: ["barbell hip thrust"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "bench", "dumbbell"],
    roleTags: ["secondary", "accessory"],
    family: "hinge_pattern",
    fatigue: "medium",
    compound: true,
  }),
  seedExercise({
    key: "glute_bridge",
    canonicalName: "Glute Bridge",
    aliases: ["barbell glute bridge", "bodyweight glute bridge"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "dumbbell", "bodyweight"],
    roleTags: ["accessory", "pump"],
    family: "hinge_pattern",
    fatigue: "low",
    compound: true,
  }),
  seedExercise({
    key: "back_extension",
    canonicalName: "Back Extension",
    aliases: ["roman chair back extension", "hyperextension"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes", "upper_back"],
    equipment: ["other", "machine"],
    roleTags: ["secondary", "accessory"],
    family: "hinge_pattern",
    fatigue: "low",
    compound: true,
  }),
  seedExercise({
    key: "band_pull_through",
    canonicalName: "Band Pull-Through",
    aliases: ["pull through", "banded pull through"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: [],
    equipment: ["band"],
    roleTags: ["accessory", "pump"],
    family: "hinge_pattern",
    fatigue: "low",
    compound: true,
  }),
  seedExercise({
    key: "lying_leg_curl",
    canonicalName: "Lying Leg Curl",
    aliases: ["lying hamstring curl"],
    movementPatterns: ["knee_flexion"],
    primaryMuscles: ["hamstrings"],
    equipment: ["machine", "band"],
    roleTags: ["secondary", "accessory"],
    family: "hamstring_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "band_leg_curl",
    canonicalName: "Band Leg Curl",
    aliases: ["band hamstring curl"],
    movementPatterns: ["knee_flexion"],
    primaryMuscles: ["hamstrings"],
    equipment: ["band"],
    roleTags: ["accessory", "pump"],
    family: "hamstring_isolation",
    fatigue: "low",
    compound: false,
  }),
  seedExercise({
    key: "single_leg_calf_raise",
    canonicalName: "Single-Leg Calf Raise",
    aliases: ["single leg calf raise"],
    movementPatterns: ["calves"],
    primaryMuscles: ["calves"],
    equipment: ["bodyweight", "dumbbell"],
    roleTags: ["accessory", "pump"],
    family: "calf_isolation",
    fatigue: "low",
    compound: false,
    unilateral: true,
  }),
  seedExercise({
    key: "close_grip_push_up",
    canonicalName: "Close-Grip Push-Up",
    aliases: ["diamond push up", "diamond pushup"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_delts"],
    equipment: ["bodyweight"],
    roleTags: ["pump", "accessory"],
    family: "triceps_isolation",
    fatigue: "low",
    compound: true,
  }),
];

const EXERCISE_BY_KEY = new Map<ExerciseKey, ExerciseDefinition>(EXERCISES.map((exercise) => [exercise.key, exercise]));
const EXERCISE_BY_ID = new Map<string, ExerciseDefinition>(EXERCISES.map((exercise) => [exercise.id, exercise]));
const ALIAS_TO_KEY = new Map<string, ExerciseKey>();

for (const exercise of EXERCISES) {
  for (const alias of exercise.aliases) {
    if (!ALIAS_TO_KEY.has(alias)) {
      ALIAS_TO_KEY.set(alias, exercise.key);
    }
  }
}

type SlotRule = {
  patterns?: MovementPattern[];
  anyRoles?: RoleTag[];
  allRoles?: RoleTag[];
  families?: string[];
  excludeKeys?: ExerciseKey[];
};

const SLOT_RULES: Record<Slot, SlotRule> = {
  PrimaryPress: { patterns: ["horizontal_push"], anyRoles: ["anchor", "primary"] },
  SecondaryPress: { patterns: ["horizontal_push", "vertical_push"], anyRoles: ["primary", "secondary"] },
  Shoulders: { patterns: ["vertical_push", "rear_delt"], anyRoles: ["secondary", "accessory", "pump"] },
  Triceps: { patterns: ["elbow_extension", "vertical_push"], families: ["triceps_isolation", "dip_pattern"] },
  Pump: { patterns: ["horizontal_push", "vertical_push", "elbow_extension"], anyRoles: ["pump", "accessory"] },
  PrimaryRow: { patterns: ["horizontal_pull"], anyRoles: ["anchor", "primary"] },
  VerticalPull: { patterns: ["vertical_pull"], anyRoles: ["anchor", "primary", "secondary", "accessory", "pump"] },
  SecondaryRow: { patterns: ["horizontal_pull"], anyRoles: ["secondary", "accessory", "primary", "pump"] },
  RearDelts: { patterns: ["rear_delt", "other"], anyRoles: ["accessory", "pump"] },
  Biceps: { patterns: ["elbow_flexion"], anyRoles: ["accessory", "pump"] },
  PrimarySquat: { patterns: ["squat"], anyRoles: ["anchor", "primary"], excludeKeys: ["leg_extension", "leg_press_calf_raise"] },
  Hinge: { patterns: ["hinge", "knee_flexion"], anyRoles: ["anchor", "primary", "secondary"] },
  SecondaryQuad: { patterns: ["squat", "lunge"], anyRoles: ["secondary", "accessory"], excludeKeys: ["ssb_squat", "squat", "leg_press_calf_raise"] },
  Hamstrings: { patterns: ["hinge", "knee_flexion"], anyRoles: ["secondary", "accessory", "primary"] },
  Calves: { patterns: ["calves"], anyRoles: ["accessory", "pump"] },
};

const SLOT_ORDER: Record<Slot, ExerciseKey[]> = {
  PrimaryPress: ["bench_press", "paused_bench_press", "close_grip_bench_press", "incline_bench_press", "dumbbell_bench_press", "incline_dumbbell_press", "feet_up_bench_press", "larsen_press", "chest_press"],
  SecondaryPress: ["incline_bench_press", "incline_dumbbell_press", "overhead_press", "dumbbell_bench_press", "seated_dumbbell_press", "shoulder_press", "arnold_press", "feet_up_bench_press", "larsen_press"],
  Shoulders: ["overhead_press", "seated_dumbbell_press", "shoulder_press", "arnold_press", "lateral_raise", "leaning_lateral_raise", "cable_lateral_raise", "front_raise", "rear_delt_fly"],
  Triceps: ["dip", "close_grip_bench_press", "triceps_pressdown", "overhead_triceps_extension", "skullcrusher", "close_grip_push_up"],
  Pump: ["lateral_raise", "leaning_lateral_raise", "cable_lateral_raise", "triceps_pressdown", "push_up", "weighted_push_up", "band_resisted_push_up", "close_grip_push_up", "pec_deck"],
  PrimaryRow: ["barbell_row", "underhand_barbell_row", "chest_supported_row", "seal_row", "incline_dumbbell_row", "seated_cable_row", "t_bar_row"],
  VerticalPull: ["pull_up", "weighted_pull_up", "chin_up", "weighted_chin_up", "lat_pulldown", "assisted_pull_up", "band_assisted_chin_up", "straight_arm_pulldown", "dumbbell_pullover", "scapular_pull_up", "serratus_pushdown"],
  SecondaryRow: ["chest_supported_row", "incline_dumbbell_row", "one_arm_dumbbell_row", "lat_focus_row", "seated_cable_row", "band_row", "scapular_row", "barbell_row", "seal_row", "t_bar_row", "barbell_shrug", "dumbbell_shrug", "behind_back_shrug", "band_shrug"],
  RearDelts: ["face_pull", "rear_delt_fly", "incline_rear_delt_raise", "rear_delt_row", "band_pull_apart", "prone_y_raise", "trap_3_raise", "reverse_pec_deck", "scapular_push_up", "wall_slide"],
  Biceps: ["hammer_curl", "curl", "incline_dumbbell_curl", "preacher_curl"],
  PrimarySquat: ["ssb_squat", "squat", "high_bar_squat", "box_squat", "leverage_squat"],
  Hinge: ["romanian_deadlift", "stiff_leg_deadlift", "deadlift", "good_morning", "hip_thrust", "back_extension", "band_pull_through", "hamstring_curl"],
  SecondaryQuad: ["leg_extension", "split_squat", "bulgarian_split_squat", "step_up", "goblet_squat", "heel_elevated_squat"],
  Hamstrings: ["hamstring_curl", "lying_leg_curl", "band_leg_curl", "romanian_deadlift", "stiff_leg_deadlift", "glute_ham_raise", "seated_leg_curl", "hip_thrust", "back_extension"],
  Calves: ["calf_raise", "single_leg_calf_raise", "seated_calf_raise", "leg_press_calf_raise"],
};

function matchesSlotRule(exercise: ExerciseDefinition, rule: SlotRule): boolean {
  if (rule.patterns?.length) {
    const patternMatch = exercise.movementPatterns.some((pattern) => rule.patterns?.includes(pattern));
    if (!patternMatch) return false;
  }
  if (rule.anyRoles?.length) {
    const roleMatch = exercise.roleTags.some((role) => rule.anyRoles?.includes(role));
    if (!roleMatch) return false;
  }
  if (rule.allRoles?.length) {
    const allMatch = rule.allRoles.every((role) => exercise.roleTags.includes(role));
    if (!allMatch) return false;
  }
  if (rule.families?.length && !rule.families.includes(exercise.family)) {
    return false;
  }
  if (rule.excludeKeys?.includes(exercise.key)) {
    return false;
  }
  return exercise.active !== false;
}

function orderedUniqueKeys(keys: ExerciseKey[]): ExerciseKey[] {
  return [...new Set(keys.filter(Boolean))];
}

export function getAllExercises(): ExerciseDefinition[] {
  return [...EXERCISES];
}

export function getExerciseByKey(key: string): ExerciseDefinition | null {
  return EXERCISE_BY_KEY.get(String(key || "").trim()) ?? null;
}

export function getExerciseById(id: string): ExerciseDefinition | null {
  return EXERCISE_BY_ID.get(String(id || "").trim()) ?? null;
}

export function resolveExerciseAlias(input: string): ExerciseKey | null {
  return ALIAS_TO_KEY.get(normalizeAlias(input)) ?? null;
}

export function getExercisesForSlot(slot: Slot): ExerciseDefinition[] {
  const rule = SLOT_RULES[slot];
  const orderedKeys = SLOT_ORDER[slot];
  const matched = EXERCISES.filter((exercise) => matchesSlotRule(exercise, rule));
  const matchedByKey = new Map(matched.map((exercise) => [exercise.key, exercise]));

  const ordered = orderedKeys
    .map((key) => matchedByKey.get(key) ?? null)
    .filter((exercise): exercise is ExerciseDefinition => !!exercise);

  const fallback = matched
    .filter((exercise) => !orderedKeys.includes(exercise.key))
    .sort((a, b) => a.canonicalName.localeCompare(b.canonicalName));

  return [...ordered, ...fallback];
}

export function getExerciseKeysForSlot(slot: Slot): ExerciseKey[] {
  return orderedUniqueKeys(getExercisesForSlot(slot).map((exercise) => exercise.key));
}
