import type { ExerciseDefinition, ExerciseKey, MovementPattern, MuscleTag, RoleTag } from "./exerciseTypes";
import type { Slot } from "./slotTypes";

type SlotQuery = {
  anyMovement?: readonly MovementPattern[];
  anyPrimaryMuscle?: readonly MuscleTag[];
  anyRole?: readonly RoleTag[];
  compound?: boolean;
  preferredOrder: readonly ExerciseKey[];
};

const EXERCISES: ExerciseDefinition[] = [
  {
    id: "bench_press",
    key: "bench_press",
    canonicalName: "Bench Press",
    aliases: ["bp", "bench", "bench press", "benchpress", "barbell bench", "barbell bench press", "flat bench", "flat bench press", "bb bench"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["barbell", "bench", "rack"],
    roleTags: ["anchor", "primary"],
    family: "bench_press",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "incline_bench_press",
    key: "incline_bench_press",
    canonicalName: "Incline Bench Press",
    aliases: ["incline bench", "incline bench press", "inclinebench", "inclinebenchpress", "incline barbell bench"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["barbell", "bench", "rack"],
    roleTags: ["primary", "secondary"],
    family: "bench_press",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "dumbbell_bench_press",
    key: "dumbbell_bench_press",
    canonicalName: "DB Bench Press",
    aliases: ["db bench", "db bench press", "dumbbell bench", "dumbbell bench press", "dbbp"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["dumbbell", "bench"],
    roleTags: ["primary", "secondary"],
    family: "bench_press",
    fatigue: "medium",
    compound: true,
    active: true,
  },
  {
    id: "chest_press",
    key: "chest_press",
    canonicalName: "Chest Press",
    aliases: ["chest press", "machine chest press"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["machine"],
    roleTags: ["primary", "secondary"],
    family: "chest_press",
    fatigue: "medium",
    compound: true,
    active: true,
  },
  {
    id: "overhead_press",
    key: "overhead_press",
    canonicalName: "Overhead Press",
    aliases: ["ohp", "overhead press", "military press"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["triceps", "chest"],
    equipment: ["barbell", "rack"],
    roleTags: ["primary", "secondary"],
    family: "overhead_press",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "shoulder_press",
    key: "shoulder_press",
    canonicalName: "Shoulder Press",
    aliases: ["shoulder press", "db shoulder press", "dumbbell shoulder press"],
    movementPatterns: ["vertical_push"],
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbell", "machine"],
    roleTags: ["secondary", "accessory"],
    family: "overhead_press",
    fatigue: "medium",
    compound: true,
    active: true,
  },
  {
    id: "lateral_raise",
    key: "lateral_raise",
    canonicalName: "Lateral Raise",
    aliases: ["lateral raise", "db lateral raise", "side raise"],
    movementPatterns: ["lateral_delt"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "lateral_raise",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "rear_delt_fly",
    key: "rear_delt_fly",
    canonicalName: "Rear Delt Fly",
    aliases: ["rear delt fly", "rear delt raise", "rear fly"],
    movementPatterns: ["rear_delt"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["upper_back"],
    equipment: ["dumbbell", "machine", "cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "rear_delt_fly",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "dip",
    key: "dip",
    canonicalName: "Dip",
    aliases: ["dip", "dips"],
    movementPatterns: ["horizontal_push", "elbow_extension"],
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_delts"],
    equipment: ["bodyweight"],
    roleTags: ["primary", "accessory"],
    family: "dip",
    fatigue: "medium",
    compound: true,
    active: true,
  },
  {
    id: "triceps_pressdown",
    key: "triceps_pressdown",
    canonicalName: "Triceps Pressdown",
    aliases: ["triceps pressdown", "pressdown", "pushdown", "triceps pushdown"],
    movementPatterns: ["elbow_extension"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "triceps_extension",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "overhead_triceps_extension",
    key: "overhead_triceps_extension",
    canonicalName: "Overhead Triceps Extension",
    aliases: ["overhead triceps extension", "overhead tricep extension", "triceps extension"],
    movementPatterns: ["elbow_extension"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "cable", "band"],
    roleTags: ["accessory"],
    family: "triceps_extension",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "skullcrusher",
    key: "skullcrusher",
    canonicalName: "Skullcrusher",
    aliases: ["skullcrusher", "skullcrushers", "lying triceps extension"],
    movementPatterns: ["elbow_extension"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["barbell", "dumbbell", "bench"],
    roleTags: ["accessory"],
    family: "triceps_extension",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "push_up",
    key: "push_up",
    canonicalName: "Push-Up",
    aliases: ["push up", "pushup", "push-up"],
    movementPatterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    equipment: ["bodyweight"],
    roleTags: ["accessory", "pump"],
    family: "push_up",
    fatigue: "low",
    compound: true,
    active: true,
  },
  {
    id: "pec_deck",
    key: "pec_deck",
    canonicalName: "Pec Deck",
    aliases: ["pec deck", "pecdeck", "chest fly machine"],
    movementPatterns: ["chest_isolation"],
    primaryMuscles: ["chest"],
    secondaryMuscles: [],
    equipment: ["machine"],
    roleTags: ["pump"],
    family: "chest_fly",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "barbell_row",
    key: "barbell_row",
    canonicalName: "Barbell Row",
    aliases: ["barbell row", "bent over row", "bb row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["rear_delts", "biceps"],
    equipment: ["barbell"],
    roleTags: ["anchor", "primary"],
    family: "row",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "chest_supported_row",
    key: "chest_supported_row",
    canonicalName: "Chest Supported Row",
    aliases: ["chest supported row", "chest supported rows"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["rear_delts", "biceps"],
    equipment: ["bench", "dumbbell", "machine"],
    roleTags: ["primary", "secondary"],
    family: "row",
    fatigue: "medium",
    compound: true,
    active: true,
  },
  {
    id: "seated_cable_row",
    key: "seated_cable_row",
    canonicalName: "Seated Cable Row",
    aliases: ["seated cable row", "cable row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["cable"],
    roleTags: ["primary", "secondary"],
    family: "row",
    fatigue: "medium",
    compound: true,
    active: true,
  },
  {
    id: "t_bar_row",
    key: "t_bar_row",
    canonicalName: "T-Bar Row",
    aliases: ["t bar row", "t-bar row", "tbar row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["machine", "barbell"],
    roleTags: ["primary"],
    family: "row",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "pull_up",
    key: "pull_up",
    canonicalName: "Pull-Up",
    aliases: ["pull up", "pullup", "pull-up"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "upper_back"],
    equipment: ["bodyweight"],
    roleTags: ["anchor", "primary"],
    family: "vertical_pull",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "chin_up",
    key: "chin_up",
    canonicalName: "Chin-Up",
    aliases: ["chin up", "chinup", "chin-up"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["upper_back"],
    equipment: ["bodyweight"],
    roleTags: ["anchor", "primary"],
    family: "vertical_pull",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "lat_pulldown",
    key: "lat_pulldown",
    canonicalName: "Lat Pulldown",
    aliases: ["lat pulldown", "latpulldown"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "upper_back"],
    equipment: ["cable", "machine"],
    roleTags: ["primary", "secondary"],
    family: "vertical_pull",
    fatigue: "medium",
    compound: true,
    active: true,
  },
  {
    id: "assisted_pull_up",
    key: "assisted_pull_up",
    canonicalName: "Assisted Pull-Up",
    aliases: ["assisted pull up", "assisted pull-up", "band assisted pull up"],
    movementPatterns: ["vertical_pull"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "upper_back"],
    equipment: ["bodyweight", "band", "machine"],
    roleTags: ["secondary"],
    family: "vertical_pull",
    fatigue: "medium",
    compound: true,
    active: true,
  },
  {
    id: "one_arm_dumbbell_row",
    key: "one_arm_dumbbell_row",
    canonicalName: "One-Arm Dumbbell Row",
    aliases: ["one arm dumbbell row", "one-arm dumbbell row", "db row", "single arm dumbbell row"],
    movementPatterns: ["horizontal_pull"],
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["dumbbell", "bench"],
    roleTags: ["secondary"],
    family: "row",
    fatigue: "medium",
    compound: true,
    unilateral: true,
    active: true,
  },
  {
    id: "face_pull",
    key: "face_pull",
    canonicalName: "Face Pull",
    aliases: ["face pull", "facepull"],
    movementPatterns: ["rear_delt", "horizontal_pull"],
    primaryMuscles: ["rear_delts", "upper_back"],
    secondaryMuscles: [],
    equipment: ["cable", "band"],
    roleTags: ["accessory", "pump"],
    family: "rear_delt",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "reverse_pec_deck",
    key: "reverse_pec_deck",
    canonicalName: "Reverse Pec Deck",
    aliases: ["reverse pec deck", "reverse pecdeck"],
    movementPatterns: ["rear_delt"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["upper_back"],
    equipment: ["machine"],
    roleTags: ["accessory", "pump"],
    family: "rear_delt",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "band_pull_apart",
    key: "band_pull_apart",
    canonicalName: "Band Pull-Apart",
    aliases: ["band pull apart", "band pull-apart"],
    movementPatterns: ["rear_delt"],
    primaryMuscles: ["rear_delts", "upper_back"],
    secondaryMuscles: [],
    equipment: ["band"],
    roleTags: ["accessory", "pump"],
    family: "rear_delt",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "hammer_curl",
    key: "hammer_curl",
    canonicalName: "Hammer Curl",
    aliases: ["hammer curl", "hammercurl"],
    movementPatterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "cable", "band"],
    roleTags: ["accessory"],
    family: "curl",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "curl",
    key: "curl",
    canonicalName: "Curl",
    aliases: ["curl", "curls", "bicep curl"],
    movementPatterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell", "dumbbell", "cable", "band"],
    roleTags: ["accessory"],
    family: "curl",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "incline_dumbbell_curl",
    key: "incline_dumbbell_curl",
    canonicalName: "Incline Dumbbell Curl",
    aliases: ["incline dumbbell curl", "incline db curl"],
    movementPatterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "bench"],
    roleTags: ["accessory"],
    family: "curl",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "preacher_curl",
    key: "preacher_curl",
    canonicalName: "Preacher Curl",
    aliases: ["preacher curl", "preachercurl"],
    movementPatterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell", "dumbbell", "machine"],
    roleTags: ["accessory"],
    family: "curl",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "ssb_squat",
    key: "ssb_squat",
    canonicalName: "SSB Squat",
    aliases: ["ssb squat", "safety squat bar squat"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["ssb", "rack"],
    roleTags: ["anchor", "primary"],
    family: "squat",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "squat",
    key: "squat",
    canonicalName: "Squat",
    aliases: ["squat", "back squat"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "rack"],
    roleTags: ["anchor", "primary"],
    family: "squat",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "romanian_deadlift",
    key: "romanian_deadlift",
    canonicalName: "Romanian Deadlift",
    aliases: ["romanian deadlift", "rdl"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["upper_back"],
    equipment: ["barbell", "dumbbell"],
    roleTags: ["anchor", "primary", "secondary"],
    family: "hinge",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "deadlift",
    key: "deadlift",
    canonicalName: "Deadlift",
    aliases: ["deadlift", "conventional deadlift"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["upper_back"],
    equipment: ["barbell"],
    roleTags: ["anchor", "primary"],
    family: "hinge",
    fatigue: "high",
    compound: true,
    active: true,
  },
  {
    id: "good_morning",
    key: "good_morning",
    canonicalName: "Good Morning",
    aliases: ["good morning", "goodmorning"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["upper_back"],
    equipment: ["barbell"],
    roleTags: ["secondary"],
    family: "hinge",
    fatigue: "medium",
    compound: true,
    active: true,
  },
  {
    id: "hamstring_curl",
    key: "hamstring_curl",
    canonicalName: "Hamstring Curl",
    aliases: ["hamstring curl", "leg curl"],
    movementPatterns: ["knee_flexion"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["machine", "band"],
    roleTags: ["secondary", "accessory"],
    family: "hamstring_curl",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "leg_extension",
    key: "leg_extension",
    canonicalName: "Leg Extension",
    aliases: ["leg extension", "legextension"],
    movementPatterns: ["knee_extension"],
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: ["machine"],
    roleTags: ["secondary", "accessory"],
    family: "leg_extension",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "split_squat",
    key: "split_squat",
    canonicalName: "Split Squat",
    aliases: ["split squat", "splitsquat", "bulgarian split squat"],
    movementPatterns: ["split_squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight", "dumbbell", "barbell"],
    roleTags: ["secondary"],
    family: "split_squat",
    fatigue: "medium",
    compound: true,
    unilateral: true,
    active: true,
  },
  {
    id: "glute_ham_raise",
    key: "glute_ham_raise",
    canonicalName: "Glute-Ham Raise",
    aliases: ["glute ham raise", "ghr"],
    movementPatterns: ["knee_flexion", "hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: [],
    equipment: ["machine", "bodyweight"],
    roleTags: ["accessory"],
    family: "hamstring_curl",
    fatigue: "medium",
    compound: true,
    active: true,
  },
  {
    id: "seated_leg_curl",
    key: "seated_leg_curl",
    canonicalName: "Seated Leg Curl",
    aliases: ["seated leg curl", "seatedlegcurl"],
    movementPatterns: ["knee_flexion"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["machine"],
    roleTags: ["accessory"],
    family: "hamstring_curl",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "calf_raise",
    key: "calf_raise",
    canonicalName: "Calf Raise",
    aliases: ["calf raise", "standing calf raise"],
    movementPatterns: ["calves"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["bodyweight", "machine", "barbell", "dumbbell"],
    roleTags: ["accessory", "pump"],
    family: "calf_raise",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "seated_calf_raise",
    key: "seated_calf_raise",
    canonicalName: "Seated Calf Raise",
    aliases: ["seated calf raise", "seatedcalfraise"],
    movementPatterns: ["calves"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine", "dumbbell"],
    roleTags: ["accessory", "pump"],
    family: "calf_raise",
    fatigue: "low",
    compound: false,
    active: true,
  },
  {
    id: "leg_press_calf_raise",
    key: "leg_press_calf_raise",
    canonicalName: "Leg Press Calf Raise",
    aliases: ["leg press calf raise", "legpresscalfraise"],
    movementPatterns: ["calves"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine"],
    roleTags: ["pump"],
    family: "calf_raise",
    fatigue: "low",
    compound: false,
    active: true,
  },
];

const EXERCISE_BY_KEY = new Map<ExerciseKey, ExerciseDefinition>();
const EXERCISE_BY_ID = new Map<string, ExerciseDefinition>();
const ALIAS_TO_KEY = new Map<string, ExerciseKey>();

function normalizeExerciseLookup(input: string): string {
  return String(input || "")
    .toLowerCase()
    .trim()
    .replace(/[_\-]/g, " ")
    .replace(/[^a-z0-9\s]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function compactExerciseLookup(input: string): string {
  return normalizeExerciseLookup(input).replace(/\s+/g, "");
}

for (const exercise of EXERCISES) {
  EXERCISE_BY_KEY.set(exercise.key, exercise);
  EXERCISE_BY_ID.set(exercise.id, exercise);
  ALIAS_TO_KEY.set(compactExerciseLookup(exercise.key), exercise.key);
  ALIAS_TO_KEY.set(compactExerciseLookup(exercise.canonicalName), exercise.key);
  for (const alias of exercise.aliases) {
    ALIAS_TO_KEY.set(compactExerciseLookup(alias), exercise.key);
  }
}

const SLOT_QUERY_ADAPTER: Record<Slot, SlotQuery> = {
  PrimaryPress: {
    anyMovement: ["horizontal_push"],
    anyRole: ["anchor", "primary"],
    compound: true,
    preferredOrder: ["bench_press", "incline_bench_press", "dumbbell_bench_press", "chest_press"],
  },
  SecondaryPress: {
    anyMovement: ["horizontal_push", "vertical_push"],
    anyRole: ["primary", "secondary"],
    compound: true,
    preferredOrder: ["incline_bench_press", "overhead_press", "dumbbell_bench_press", "shoulder_press"],
  },
  Shoulders: {
    anyMovement: ["vertical_push", "lateral_delt", "rear_delt"],
    anyPrimaryMuscle: ["front_delts", "side_delts", "rear_delts"],
    anyRole: ["secondary", "accessory", "pump"],
    preferredOrder: ["overhead_press", "shoulder_press", "lateral_raise", "rear_delt_fly"],
  },
  Triceps: {
    anyMovement: ["elbow_extension", "horizontal_push"],
    anyPrimaryMuscle: ["triceps"],
    anyRole: ["primary", "accessory", "pump"],
    preferredOrder: ["dip", "triceps_pressdown", "overhead_triceps_extension", "skullcrusher"],
  },
  Pump: {
    anyMovement: ["lateral_delt", "elbow_extension", "horizontal_push", "chest_isolation"],
    anyRole: ["accessory", "pump"],
    preferredOrder: ["lateral_raise", "triceps_pressdown", "push_up", "pec_deck"],
  },
  PrimaryRow: {
    anyMovement: ["horizontal_pull"],
    anyRole: ["anchor", "primary"],
    compound: true,
    preferredOrder: ["barbell_row", "chest_supported_row", "seated_cable_row", "t_bar_row"],
  },
  VerticalPull: {
    anyMovement: ["vertical_pull"],
    anyRole: ["anchor", "primary", "secondary"],
    compound: true,
    preferredOrder: ["pull_up", "chin_up", "lat_pulldown", "assisted_pull_up"],
  },
  SecondaryRow: {
    anyMovement: ["horizontal_pull"],
    anyRole: ["primary", "secondary"],
    compound: true,
    preferredOrder: ["chest_supported_row", "seated_cable_row", "barbell_row", "one_arm_dumbbell_row"],
  },
  RearDelts: {
    anyMovement: ["rear_delt"],
    anyPrimaryMuscle: ["rear_delts"],
    anyRole: ["accessory", "pump"],
    preferredOrder: ["face_pull", "rear_delt_fly", "reverse_pec_deck", "band_pull_apart"],
  },
  Biceps: {
    anyMovement: ["elbow_flexion"],
    anyPrimaryMuscle: ["biceps"],
    anyRole: ["accessory"],
    preferredOrder: ["hammer_curl", "curl", "incline_dumbbell_curl", "preacher_curl"],
  },
  PrimarySquat: {
    anyMovement: ["squat"],
    anyRole: ["anchor", "primary"],
    compound: true,
    preferredOrder: ["ssb_squat", "squat"],
  },
  Hinge: {
    anyMovement: ["hinge", "knee_flexion"],
    anyPrimaryMuscle: ["hamstrings"],
    anyRole: ["anchor", "primary", "secondary", "accessory"],
    preferredOrder: ["romanian_deadlift", "deadlift", "good_morning", "hamstring_curl"],
  },
  SecondaryQuad: {
    anyMovement: ["knee_extension", "split_squat"],
    anyPrimaryMuscle: ["quads"],
    anyRole: ["secondary", "accessory"],
    preferredOrder: ["leg_extension", "split_squat"],
  },
  Hamstrings: {
    anyMovement: ["knee_flexion", "hinge"],
    anyPrimaryMuscle: ["hamstrings"],
    anyRole: ["secondary", "accessory"],
    preferredOrder: ["hamstring_curl", "romanian_deadlift", "glute_ham_raise", "seated_leg_curl"],
  },
  Calves: {
    anyMovement: ["calves"],
    anyPrimaryMuscle: ["calves"],
    anyRole: ["accessory", "pump"],
    preferredOrder: ["calf_raise", "seated_calf_raise", "leg_press_calf_raise"],
  },
};

function uniqueKeys(items: readonly ExerciseDefinition[]): ExerciseKey[] {
  const seen = new Set<string>();
  const ordered: ExerciseKey[] = [];
  for (const item of items) {
    if (seen.has(item.key)) continue;
    seen.add(item.key);
    ordered.push(item.key);
  }
  return ordered;
}

function matchesAny<T extends string>(needle: readonly T[] | undefined, haystack: readonly T[]): boolean {
  if (!needle || needle.length === 0) return true;
  return needle.some((value) => haystack.includes(value));
}

function matchesSlotQuery(exercise: ExerciseDefinition, query: SlotQuery): boolean {
  if (query.compound !== undefined && Boolean(exercise.compound) !== query.compound) return false;
  if (!matchesAny(query.anyMovement, exercise.movementPatterns)) return false;
  if (!matchesAny(query.anyRole, exercise.roleTags)) return false;
  if (!matchesAny(query.anyPrimaryMuscle, exercise.primaryMuscles)) return false;
  return exercise.active !== false;
}

export function getAllExercises(): ExerciseDefinition[] {
  return [...EXERCISES];
}

export function getExerciseByKey(key: string): ExerciseDefinition | null {
  return EXERCISE_BY_KEY.get(String(key || "").trim()) ?? null;
}

export function getExerciseById(id: string): ExerciseDefinition | null {
  return EXERCISE_BY_ID.get(String(id || "").trim()) ?? null;
}

export function resolveExerciseAlias(input: string): string | null {
  return ALIAS_TO_KEY.get(compactExerciseLookup(input)) ?? null;
}

export function getExercisesForSlot(slot: Slot): ExerciseDefinition[] {
  const query = SLOT_QUERY_ADAPTER[slot];
  const preferred = query.preferredOrder
    .map((key) => getExerciseByKey(key))
    .filter((item): item is ExerciseDefinition => !!item)
    .filter((item) => matchesSlotQuery(item, query));

  const preferredSet = new Set(preferred.map((item) => item.key));
  const fallback = EXERCISES.filter((item) => !preferredSet.has(item.key) && matchesSlotQuery(item, query));
  return [...preferred, ...fallback];
}

export function getExerciseKeysForSlot(slot: Slot): string[] {
  return uniqueKeys(getExercisesForSlot(slot));
}
